export const GET_ALERTS_PENDING : string = 'GET_ALERTS_PENDING';
export const GET_ALERTS_FAILURE : string = 'GET_ALERTS_FAILURE';
export const GET_ALERTS_SUCCESS : string = 'GET_ALERTS_SUCCESS';
export const CREATE_ALERT_PENDING = 'CREATE_ALERT_PENDING';
export const CREATE_ALERT_FAILURE = 'CREATE_ALERT_FAILURE';
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS';

