export const GET_ALERTS_PENDING : string = 'GET_ALERTS_PENDING';
export const GET_ALERTS_FAILURE : string = 'GET_ALERTS_FAILURE';
export const GET_ALERTS_SUCCESS : string = 'GET_ALERTS_SUCCESS';
export const CREATE_ALERT_PENDING : string = 'CREATE_ALERT_PENDING';
export const CREATE_ALERT_FAILURE : string = 'CREATE_ALERT_FAILURE';
export const CREATE_ALERT_SUCCESS : string = 'CREATE_ALERT_SUCCESS';
export const DELETE_ALERT_PENDING : string = 'DELETE_ALERT_PENDING';
export const DELETE_ALERT_FAILURE : string = 'DELETE_ALERT_FAILURE';
export const DELETE_ALERT_SUCCESS : string = 'DELETE_ALERT_SUCCESS';

