export const SET_FIREBASE_PENDING : string = 'SET_FIREBASE_PENDING';
export const SET_FIREBASE_SUCCESS : string = 'SET_FIREBASE_SUCCESS';
export const SET_FIREBASE_FAILURE : string = 'SET_FIREBASE_FAILURE';
export const SET_FIREBASE_ADMIN_PENDING : string = 'SET_FIREBASE_ADMIN_PENDING';
export const SET_FIREBASE_ADMIN_SUCCESS : string = 'SET_FIREBASE_ADMIN_SUCCESS';
export const SET_FIREBASE_ADMIN_FAILURE : string = 'SET_FIREBASE_ADMIN_FAILURE';

