export const GET_COUNTRIES_PENDING : string = 'GET_COUNTRIES_PENDING';
export const GET_COUNTRIES_SUCCESS : string = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILURE : string = 'GET_COUNTRIES_FAILURE';
