//this will go on the server most likely

export const renderIcon = (symbol : string) => {

    switch (symbol.toLowerCase()) {
        case '$pac':
            return require('../../assets/coin-icons/$pac.png')
        case 'abt':
            return require('../../assets/coin-icons/abt.png')
        case 'act':
            return require('../../assets/coin-icons/act.png')
        case 'actn':
            return require('../../assets/coin-icons/actn.png')
        case 'ada':
            return require('../../assets/coin-icons/ada.png')
        case 'add':
            return require('../../assets/coin-icons/add.png')
        case 'adx':
            return require('../../assets/coin-icons/adx.png')
        case 'ae':
            return require('../../assets/coin-icons/ae.png')
        case 'aeon':
            return require('../../assets/coin-icons/aeon.png')
        case 'aeur':
            return require('../../assets/coin-icons/aeur.png')
        case 'agi':
            return require('../../assets/coin-icons/agi.png')
        case 'agrs':
            return require('../../assets/coin-icons/agrs.png')
        case 'aion':
            return require('../../assets/coin-icons/aion.png')
        case 'amb':
            return require('../../assets/coin-icons/amb.png')
        case 'amp':
            return require('../../assets/coin-icons/amp.png')
        case 'ant':
            return require('../../assets/coin-icons/ant.png')
        case 'apex':
            return require('../../assets/coin-icons/apex.png')
        case 'appc':
            return require('../../assets/coin-icons/appc.png')
        case 'ardr':
            return require('../../assets/coin-icons/ardr.png')
        case 'arg':
            return require('../../assets/coin-icons/arg.png')
        case 'ark':
            return require('../../assets/coin-icons/ark.png')
        case 'arn':
            return require('../../assets/coin-icons/arn.png')
        case 'ary':
            return require('../../assets/coin-icons/ary.png')
        case 'ast':
            return require('../../assets/coin-icons/ast.png')
        case 'atm':
            return require('../../assets/coin-icons/atm.png')
        case 'atom':
            return require('../../assets/coin-icons/atom.png')
        case 'audr':
            return require('../../assets/coin-icons/audr.png')
        case 'auto':
            return require('../../assets/coin-icons/auto.png')
        case 'aywa':
            return require('../../assets/coin-icons/aywa.png')
        case 'bab':
            return require('../../assets/coin-icons/bab.png')
        case 'bat':
            return require('../../assets/coin-icons/bat.png')
        case 'bay':
            return require('../../assets/coin-icons/bay.png')
        case 'bcbc':
            return require('../../assets/coin-icons/bcbc.png')
        case 'bcc':
            return require('../../assets/coin-icons/bcc.png')
        case 'bcd':
            return require('../../assets/coin-icons/bcd.png')
        case 'bch':
            return require('../../assets/coin-icons/bch.png')
        case 'bcio':
            return require('../../assets/coin-icons/bcio.png')
        case 'bcn':
            return require('../../assets/coin-icons/bcn.png')
        case 'bco':
            return require('../../assets/coin-icons/bco.png')
        case 'bcpt':
            return require('../../assets/coin-icons/bcpt.png')
        case 'bdl':
            return require('../../assets/coin-icons/bdl.png')
        case 'beam':
            return require('../../assets/coin-icons/beam.png')
        case 'bela':
            return require('../../assets/coin-icons/bela.png')
        case 'bix':
            return require('../../assets/coin-icons/bix.png')
        case 'blcn':
            return require('../../assets/coin-icons/blcn.png')
        case 'blk':
            return require('../../assets/coin-icons/blk.png')
        case 'block':
            return require('../../assets/coin-icons/block.png')
        case 'blz':
            return require('../../assets/coin-icons/blz.png')
        case 'bnb':
            return require('../../assets/coin-icons/bnb.png')
        case 'bnt':
            return require('../../assets/coin-icons/bnt.png')
        case 'bnty':
            return require('../../assets/coin-icons/bnty.png')
        case 'booty':
            return require('../../assets/coin-icons/booty.png')
        case 'bos':
            return require('../../assets/coin-icons/bos.png')
        case 'bpt':
            return require('../../assets/coin-icons/bpt.png')
        case 'bq':
            return require('../../assets/coin-icons/bq.png')
        case 'brd':
            return require('../../assets/coin-icons/brd.png')
        case 'bsd':
            return require('../../assets/coin-icons/bsd.png')
        case 'bsv':
            return require('../../assets/coin-icons/bsv.png')
        case 'btc':
            return require('../../assets/coin-icons/btc.png')
        case 'btcd':
            return require('../../assets/coin-icons/btcd.png')
        case 'btch':
            return require('../../assets/coin-icons/btch.png')
        case 'btcp':
            return require('../../assets/coin-icons/btcp.png')
        case 'btcz':
            return require('../../assets/coin-icons/btcz.png')
        case 'btdx':
            return require('../../assets/coin-icons/btdx.png')
        case 'btg':
            return require('../../assets/coin-icons/btg.png')
        case 'btm':
            return require('../../assets/coin-icons/btm.png')
        case 'bts':
            return require('../../assets/coin-icons/bts.png')
        case 'btt':
            return require('../../assets/coin-icons/btt.png')
        case 'btx':
            return require('../../assets/coin-icons/btx.png')
        case 'burst':
            return require('../../assets/coin-icons/burst.png')
        case 'call':
            return require('../../assets/coin-icons/call.png')
        case 'cc':
            return require('../../assets/coin-icons/cc.png')
        case 'cdn':
            return require('../../assets/coin-icons/cdn.png')
        case 'cdt':
            return require('../../assets/coin-icons/cdt.png')
        case 'cenz':
            return require('../../assets/coin-icons/cenz.png')
        case 'chain':
            return require('../../assets/coin-icons/chain.png')
        case 'chat':
            return require('../../assets/coin-icons/chat.png')
        case 'chips':
            return require('../../assets/coin-icons/chips.png')
        case 'cix':
            return require('../../assets/coin-icons/cix.png')
        case 'clam':
            return require('../../assets/coin-icons/clam.png')
        case 'cloak':
            return require('../../assets/coin-icons/cloak.png')
        case 'cmm':
            return require('../../assets/coin-icons/cmm.png')
        case 'cmt':
            return require('../../assets/coin-icons/cmt.png')
        case 'cnd':
            return require('../../assets/coin-icons/cnd.png')
        case 'cnx':
            return require('../../assets/coin-icons/cnx.png')
        case 'cny':
            return require('../../assets/coin-icons/cny.png')
        case 'cob':
            return require('../../assets/coin-icons/cob.png')
        case 'colx':
            return require('../../assets/coin-icons/colx.png')
        case 'coqui':
            return require('../../assets/coin-icons/coqui.png')
        case 'cred':
            return require('../../assets/coin-icons/cred.png')
        case 'crpt':
            return require('../../assets/coin-icons/crpt.png')
        case 'crw':
            return require('../../assets/coin-icons/crw.png')
        case 'cs':
            return require('../../assets/coin-icons/cs.png')
        case 'ctr':
            return require('../../assets/coin-icons/ctr.png')
        case 'ctxc':
            return require('../../assets/coin-icons/ctxc.png')
        case 'cvc':
            return require('../../assets/coin-icons/cvc.png')
        case 'd':
            return require('../../assets/coin-icons/d.png')
        case 'dai':
            return require('../../assets/coin-icons/dai.png')
        case 'dash':
            return require('../../assets/coin-icons/dash.png')
        case 'dat':
            return require('../../assets/coin-icons/dat.png')
        case 'data':
            return require('../../assets/coin-icons/data.png')
        case 'dbc':
            return require('../../assets/coin-icons/dbc.png')
        case 'dcn':
            return require('../../assets/coin-icons/dcn.png')
        case 'dcr':
            return require('../../assets/coin-icons/dcr.png')
        case 'deez':
            return require('../../assets/coin-icons/deez.png')
        case 'dent':
            return require('../../assets/coin-icons/dent.png')
        case 'dew':
            return require('../../assets/coin-icons/dew.png')
        case 'dgb':
            return require('../../assets/coin-icons/dgb.png')
        case 'dgd':
            return require('../../assets/coin-icons/dgd.png')
        case 'dlt':
            return require('../../assets/coin-icons/dlt.png')
        case 'dnt':
            return require('../../assets/coin-icons/dnt.png')
        case 'dock':
            return require('../../assets/coin-icons/dock.png')
        case 'doge':
            return require('../../assets/coin-icons/doge.png')
        case 'drgn':
            return require('../../assets/coin-icons/drgn.png')
        case 'drop':
            return require('../../assets/coin-icons/drop.png')
        case 'dta':
            return require('../../assets/coin-icons/dta.png')
        case 'dth':
            return require('../../assets/coin-icons/dth.png')
        case 'dtr':
            return require('../../assets/coin-icons/dtr.png')
        case 'ebst':
            return require('../../assets/coin-icons/ebst.png')
        case 'eca':
            return require('../../assets/coin-icons/eca.png')
        case 'edg':
            return require('../../assets/coin-icons/edg.png')
        case 'edo':
            return require('../../assets/coin-icons/edo.png')
        case 'edoge':
            return require('../../assets/coin-icons/edoge.png')
        case 'ela':
            return require('../../assets/coin-icons/ela.png')
        case 'elec':
            return require('../../assets/coin-icons/elec.png')
        case 'elf':
            return require('../../assets/coin-icons/elf.png')
        case 'elix':
            return require('../../assets/coin-icons/elix.png')
        case 'ella':
            return require('../../assets/coin-icons/ella.png')
        case 'emc':
            return require('../../assets/coin-icons/emc.png')
        case 'emc2':
            return require('../../assets/coin-icons/emc2.png')
        case 'eng':
            return require('../../assets/coin-icons/eng.png')
        case 'enj':
            return require('../../assets/coin-icons/enj.png')
        case 'entrp':
            return require('../../assets/coin-icons/entrp.png')
        case 'eon':
            return require('../../assets/coin-icons/eon.png')
        case 'eop':
            return require('../../assets/coin-icons/eop.png')
        case 'eos':
            return require('../../assets/coin-icons/eos.png')
        case 'eqli':
            return require('../../assets/coin-icons/eqli.png')
        case 'equa':
            return require('../../assets/coin-icons/equa.png')
        case 'etc':
            return require('../../assets/coin-icons/etc.png')
        case 'eth':
            return require('../../assets/coin-icons/eth.png')
        case 'ethos':
            return require('../../assets/coin-icons/ethos.png')
        case 'etn':
            return require('../../assets/coin-icons/etn.png')
        case 'etp':
            return require('../../assets/coin-icons/etp.png')
        case 'eur':
            return require('../../assets/coin-icons/eur.png')
        case 'evx':
            return require('../../assets/coin-icons/evx.png')
        case 'exmo':
            return require('../../assets/coin-icons/exmo.png')
        case 'exp':
            return require('../../assets/coin-icons/exp.png')
        case 'fair':
            return require('../../assets/coin-icons/fair.png')
        case 'fct':
            return require('../../assets/coin-icons/fct.png')
        case 'fil':
            return require('../../assets/coin-icons/fil.png')
        case 'fjc':
            return require('../../assets/coin-icons/fjc.png')
        case 'fldc':
            return require('../../assets/coin-icons/fldc.png')
        case 'flo':
            return require('../../assets/coin-icons/flo.png')
        case 'fsn':
            return require('../../assets/coin-icons/fsn.png')
        case 'ftc':
            return require('../../assets/coin-icons/ftc.png')
        case 'fuel':
            return require('../../assets/coin-icons/fuel.png')
        case 'fun':
            return require('../../assets/coin-icons/fun.png')
        case 'game':
            return require('../../assets/coin-icons/game.png')
        case 'gas':
            return require('../../assets/coin-icons/gas.png')
        case 'gbp':
            return require('../../assets/coin-icons/gbp.png')
        case 'gbx':
            return require('../../assets/coin-icons/gbx.png')
        case 'gbyte':
            return require('../../assets/coin-icons/gbyte.png')
        case 'generic':
            return require('../../assets/coin-icons/generic.png')
        case 'gin':
            return require('../../assets/coin-icons/gin.png')
        case 'glxt':
            return require('../../assets/coin-icons/glxt.png')
        case 'gmr':
            return require('../../assets/coin-icons/gmr.png')
        case 'gno':
            return require('../../assets/coin-icons/gno.png')
        case 'gnt':
            return require('../../assets/coin-icons/gnt.png')
        case 'gold':
            return require('../../assets/coin-icons/gold.png')
        case 'grc':
            return require('../../assets/coin-icons/grc.png')
        case 'grin':
            return require('../../assets/coin-icons/grin.png')
        case 'grs':
            return require('../../assets/coin-icons/grs.png')
        case 'gsc':
            return require('../../assets/coin-icons/gsc.png')
        case 'gto':
            return require('../../assets/coin-icons/gto.png')
        case 'gup':
            return require('../../assets/coin-icons/gup.png')
        case 'gusd':
            return require('../../assets/coin-icons/gusd.png')
        case 'gvt':
            return require('../../assets/coin-icons/gvt.png')
        case 'gxs':
            return require('../../assets/coin-icons/gxs.png')
        case 'gzr':
            return require('../../assets/coin-icons/gzr.png')
        case 'hight':
            return require('../../assets/coin-icons/hight.png')
        case 'hodl':
            return require('../../assets/coin-icons/hodl.png')
        case 'hot':
            return require('../../assets/coin-icons/hot.png')
        case 'hpb':
            return require('../../assets/coin-icons/hpb.png')
        case 'hsr':
            return require('../../assets/coin-icons/hsr.png')
        case 'ht':
            return require('../../assets/coin-icons/ht.png')
        case 'html':
            return require('../../assets/coin-icons/html.png')
        case 'huc':
            return require('../../assets/coin-icons/huc.png')
        case 'hush':
            return require('../../assets/coin-icons/hush.png')
        case 'icn':
            return require('../../assets/coin-icons/icn.png')
        case 'icx':
            return require('../../assets/coin-icons/icx.png')
        case 'ignis':
            return require('../../assets/coin-icons/ignis.png')
        case 'ilk':
            return require('../../assets/coin-icons/ilk.png')
        case 'ink':
            return require('../../assets/coin-icons/ink.png')
        case 'ins':
            return require('../../assets/coin-icons/ins.png')
        case 'ion':
            return require('../../assets/coin-icons/ion.png')
        case 'iop':
            return require('../../assets/coin-icons/iop.png')
        case 'iost':
            return require('../../assets/coin-icons/iost.png')
        case 'iotx':
            return require('../../assets/coin-icons/iotx.png')
        case 'iq':
            return require('../../assets/coin-icons/iq.png')
        case 'itc':
            return require('../../assets/coin-icons/itc.png')
        case 'jnt':
            return require('../../assets/coin-icons/jnt.png')
        case 'jpy':
            return require('../../assets/coin-icons/jpy.png')
        case 'kcs':
            return require('../../assets/coin-icons/kcs.png')
        case 'kin':
            return require('../../assets/coin-icons/kin.png')
        case 'kmd':
            return require('../../assets/coin-icons/kmd.png')
        case 'knc':
            return require('../../assets/coin-icons/knc.png')
        case 'krb':
            return require('../../assets/coin-icons/krb.png')
        case 'lbc':
            return require('../../assets/coin-icons/lbc.png')
        case 'lend':
            return require('../../assets/coin-icons/lend.png')
        case 'link':
            return require('../../assets/coin-icons/link.png')
        case 'lkk':
            return require('../../assets/coin-icons/lkk.png')
        case 'loom':
            return require('../../assets/coin-icons/loom.png')
        case 'lpt':
            return require('../../assets/coin-icons/lpt.png')
        case 'lrc':
            return require('../../assets/coin-icons/lrc.png')
        case 'lsk':
            return require('../../assets/coin-icons/lsk.png')
        case 'ltc':
            return require('../../assets/coin-icons/ltc.png')
        case 'lun':
            return require('../../assets/coin-icons/lun.png')
        case 'maid':
            return require('../../assets/coin-icons/maid.png')
        case 'mana':
            return require('../../assets/coin-icons/mana.png')
        case 'matic':
            return require('../../assets/coin-icons/matic.png')
        case 'mcap':
            return require('../../assets/coin-icons/mcap.png')
        case 'mco':
            return require('../../assets/coin-icons/mco.png')
        case 'mda':
            return require('../../assets/coin-icons/mda.png')
        case 'mds':
            return require('../../assets/coin-icons/mds.png')
        case 'med':
            return require('../../assets/coin-icons/med.png')
        case 'meetone':
            return require('../../assets/coin-icons/meetone.png')
        case 'mft':
            return require('../../assets/coin-icons/mft.png')
        case 'miota':
            return require('../../assets/coin-icons/miota.png')
        case 'mith':
            return require('../../assets/coin-icons/mith.png')
        case 'mkr':
            return require('../../assets/coin-icons/mkr.png')
        case 'mln':
            return require('../../assets/coin-icons/mln.png')
        case 'mnx':
            return require('../../assets/coin-icons/mnx.png')
        case 'mnz':
            return require('../../assets/coin-icons/mnz.png')
        case 'moac':
            return require('../../assets/coin-icons/moac.png')
        case 'mod':
            return require('../../assets/coin-icons/mod.png')
        case 'mona':
            return require('../../assets/coin-icons/mona.png')
        case 'msr':
            return require('../../assets/coin-icons/msr.png')
        case 'mth':
            return require('../../assets/coin-icons/mth.png')
        case 'mtl':
            return require('../../assets/coin-icons/mtl.png')
        case 'music':
            return require('../../assets/coin-icons/music.png')
        case 'mzc':
            return require('../../assets/coin-icons/mzc.png')
        case 'nano':
            return require('../../assets/coin-icons/nano.png')
        case 'nas':
            return require('../../assets/coin-icons/nas.png')
        case 'nav':
            return require('../../assets/coin-icons/nav.png')
        case 'ncash':
            return require('../../assets/coin-icons/ncash.png')
        case 'ndz':
            return require('../../assets/coin-icons/ndz.png')
        case 'nebl':
            return require('../../assets/coin-icons/nebl.png')
        case 'neo':
            return require('../../assets/coin-icons/neo.png')
        case 'neos':
            return require('../../assets/coin-icons/neos.png')
        case 'neu':
            return require('../../assets/coin-icons/neu.png')
        case 'nexo':
            return require('../../assets/coin-icons/nexo.png')
        case 'ngc':
            return require('../../assets/coin-icons/ngc.png')
        case 'nio':
            return require('../../assets/coin-icons/nio.png')
        case 'nlc2':
            return require('../../assets/coin-icons/nlc2.png')
        case 'nlg':
            return require('../../assets/coin-icons/nlg.png')
        case 'nmc':
            return require('../../assets/coin-icons/nmc.png')
        case 'npxs':
            return require('../../assets/coin-icons/npxs.png')
        case 'nuls':
            return require('../../assets/coin-icons/nuls.png')
        case 'nxs':
            return require('../../assets/coin-icons/nxs.png')
        case 'nxt':
            return require('../../assets/coin-icons/nxt.png')
        case 'oax':
            return require('../../assets/coin-icons/oax.png')
        case 'ok':
            return require('../../assets/coin-icons/ok.png')
        case 'omg':
            return require('../../assets/coin-icons/omg.png')
        case 'omni':
            return require('../../assets/coin-icons/omni.png')
        case 'ong':
            return require('../../assets/coin-icons/ong.png')
        case 'ont':
            return require('../../assets/coin-icons/ont.png')
        case 'oot':
            return require('../../assets/coin-icons/oot.png')
        case 'ost':
            return require('../../assets/coin-icons/ost.png')
        case 'ox':
            return require('../../assets/coin-icons/ox.png')
        case 'part':
            return require('../../assets/coin-icons/part.png')
        case 'pasc':
            return require('../../assets/coin-icons/pasc.png')
        case 'pasl':
            return require('../../assets/coin-icons/pasl.png')
        case 'pax':
            return require('../../assets/coin-icons/pax.png')
        case 'pay':
            return require('../../assets/coin-icons/pay.png')
        case 'payx':
            return require('../../assets/coin-icons/payx.png')
        case 'pink':
            return require('../../assets/coin-icons/pink.png')
        case 'pirl':
            return require('../../assets/coin-icons/pirl.png')
        case 'pivx':
            return require('../../assets/coin-icons/pivx.png')
        case 'plr':
            return require('../../assets/coin-icons/plr.png')
        case 'poa':
            return require('../../assets/coin-icons/poa.png')
        case 'poe':
            return require('../../assets/coin-icons/poe.png')
        case 'polis':
            return require('../../assets/coin-icons/polis.png')
        case 'poly':
            return require('../../assets/coin-icons/poly.png')
        case 'pot':
            return require('../../assets/coin-icons/pot.png')
        case 'powr':
            return require('../../assets/coin-icons/powr.png')
        case 'ppc':
            return require('../../assets/coin-icons/ppc.png')
        case 'ppp':
            return require('../../assets/coin-icons/ppp.png')
        case 'ppt':
            return require('../../assets/coin-icons/ppt.png')
        case 'pre':
            return require('../../assets/coin-icons/pre.png')
        case 'prl':
            return require('../../assets/coin-icons/prl.png')
        case 'pungo':
            return require('../../assets/coin-icons/pungo.png')
        case 'pura':
            return require('../../assets/coin-icons/pura.png')
        case 'qash':
            return require('../../assets/coin-icons/qash.png')
        case 'qiwi':
            return require('../../assets/coin-icons/qiwi.png')
        case 'qlc':
            return require('../../assets/coin-icons/qlc.png')
        case 'qrl':
            return require('../../assets/coin-icons/qrl.png')
        case 'qsp':
            return require('../../assets/coin-icons/qsp.png')
        case 'qtum':
            return require('../../assets/coin-icons/qtum.png')
        case 'r':
            return require('../../assets/coin-icons/r.png')
        case 'rads':
            return require('../../assets/coin-icons/rads.png')
        case 'rap':
            return require('../../assets/coin-icons/rap.png')
        case 'rcn':
            return require('../../assets/coin-icons/rcn.png')
        case 'rdd':
            return require('../../assets/coin-icons/rdd.png')
        case 'rdn':
            return require('../../assets/coin-icons/rdn.png')
        case 'ren':
            return require('../../assets/coin-icons/ren.png')
        case 'rep':
            return require('../../assets/coin-icons/rep.png')
        case 'req':
            return require('../../assets/coin-icons/req.png')
        case 'rhoc':
            return require('../../assets/coin-icons/rhoc.png')
        case 'ric':
            return require('../../assets/coin-icons/ric.png')
        case 'rise':
            return require('../../assets/coin-icons/rise.png')
        case 'rlc':
            return require('../../assets/coin-icons/rlc.png')
        case 'rpx':
            return require('../../assets/coin-icons/rpx.png')
        case 'rub':
            return require('../../assets/coin-icons/rub.png')
        case 'rvn':
            return require('../../assets/coin-icons/rvn.png')
        case 'ryo':
            return require('../../assets/coin-icons/ryo.png')
        case 'safe':
            return require('../../assets/coin-icons/safe.png')
        case 'salt':
            return require('../../assets/coin-icons/salt.png')
        case 'san':
            return require('../../assets/coin-icons/san.png')
        case 'sbd':
            return require('../../assets/coin-icons/sbd.png')
        case 'sberbank':
            return require('../../assets/coin-icons/sberbank.png')
        case 'sc':
            return require('../../assets/coin-icons/sc.png')
        case 'shift':
            return require('../../assets/coin-icons/shift.png')
        case 'sib':
            return require('../../assets/coin-icons/sib.png')
        case 'sky':
            return require('../../assets/coin-icons/sky.png')
        case 'slr':
            return require('../../assets/coin-icons/slr.png')
        case 'sls':
            return require('../../assets/coin-icons/sls.png')
        case 'smart':
            return require('../../assets/coin-icons/smart.png')
        case 'sngls':
            return require('../../assets/coin-icons/sngls.png')
        case 'snm':
            return require('../../assets/coin-icons/snm.png')
        case 'snt':
            return require('../../assets/coin-icons/snt.png')
        case 'soc':
            return require('../../assets/coin-icons/soc.png')
        case 'spank':
            return require('../../assets/coin-icons/spank.png')
        case 'sphtx':
            return require('../../assets/coin-icons/sphtx.png')
        case 'srn':
            return require('../../assets/coin-icons/srn.png')
        case 'stak':
            return require('../../assets/coin-icons/stak.png')
        case 'start':
            return require('../../assets/coin-icons/start.png')
        case 'steem':
            return require('../../assets/coin-icons/steem.png')
        case 'storj':
            return require('../../assets/coin-icons/storj.png')
        case 'storm':
            return require('../../assets/coin-icons/storm.png')
        case 'stq':
            return require('../../assets/coin-icons/stq.png')
        case 'strat':
            return require('../../assets/coin-icons/strat.png')
        case 'sub':
            return require('../../assets/coin-icons/sub.png')
        case 'sumo':
            return require('../../assets/coin-icons/sumo.png')
        case 'sys':
            return require('../../assets/coin-icons/sys.png')
        case 'taas':
            return require('../../assets/coin-icons/taas.png')
        case 'tau':
            return require('../../assets/coin-icons/tau.png')
        case 'tbx':
            return require('../../assets/coin-icons/tbx.png')
        case 'tel':
            return require('../../assets/coin-icons/tel.png')
        case 'ten':
            return require('../../assets/coin-icons/ten.png')
        case 'tern':
            return require('../../assets/coin-icons/tern.png')
        case 'tgch':
            return require('../../assets/coin-icons/tgch.png')
        case 'theta':
            return require('../../assets/coin-icons/theta.png')
        case 'tix':
            return require('../../assets/coin-icons/tix.png')
        case 'tkn':
            return require('../../assets/coin-icons/tkn.png')
        case 'tks':
            return require('../../assets/coin-icons/tks.png')
        case 'tnb':
            return require('../../assets/coin-icons/tnb.png')
        case 'tnc':
            return require('../../assets/coin-icons/tnc.png')
        case 'tnt':
            return require('../../assets/coin-icons/tnt.png')
        case 'tomo':
            return require('../../assets/coin-icons/tomo.png')
        case 'tpay':
            return require('../../assets/coin-icons/tpay.png')
        case 'trig':
            return require('../../assets/coin-icons/trig.png')
        case 'trtl':
            return require('../../assets/coin-icons/trtl.png')
        case 'trx':
            return require('../../assets/coin-icons/trx.png')
        case 'tusd':
            return require('../../assets/coin-icons/tusd.png')
        case 'tzc':
            return require('../../assets/coin-icons/tzc.png')
        case 'ubq':
            return require('../../assets/coin-icons/ubq.png')
        case 'unity':
            return require('../../assets/coin-icons/unity.png')
        case 'usd':
            return require('../../assets/coin-icons/usd.png')
        case 'usdc':
            return require('../../assets/coin-icons/usdc.png')
        case 'usdt':
            return require('../../assets/coin-icons/usdt.png')
        case 'utk':
            return require('../../assets/coin-icons/utk.png')
        case 'veri':
            return require('../../assets/coin-icons/veri.png')
        case 'vet':
            return require('../../assets/coin-icons/vet.png')
        case 'via':
            return require('../../assets/coin-icons/via.png')
        case 'vib':
            return require('../../assets/coin-icons/vib.png')
        case 'vibe':
            return require('../../assets/coin-icons/vibe.png')
        case 'vivo':
            return require('../../assets/coin-icons/vivo.png')
        case 'vrc':
            return require('../../assets/coin-icons/vrc.png')
        case 'vrsc':
            return require('../../assets/coin-icons/vrsc.png')
        case 'vtc':
            return require('../../assets/coin-icons/vtc.png')
        case 'vtho':
            return require('../../assets/coin-icons/vtho.png')
        case 'wabi':
            return require('../../assets/coin-icons/wabi.png')
        case 'wan':
            return require('../../assets/coin-icons/wan.png')
        case 'waves':
            return require('../../assets/coin-icons/waves.png')
        case 'wax':
            return require('../../assets/coin-icons/wax.png')
        case 'wgr':
            return require('../../assets/coin-icons/wgr.png')
        case 'wicc':
            return require('../../assets/coin-icons/wicc.png')
        case 'wings':
            return require('../../assets/coin-icons/wings.png')
        case 'wpr':
            return require('../../assets/coin-icons/wpr.png')
        case 'wtc':
            return require('../../assets/coin-icons/wtc.png')
        case 'x':
            return require('../../assets/coin-icons/x.png')
        case 'xas':
            return require('../../assets/coin-icons/xas.png')
        case 'xbc':
            return require('../../assets/coin-icons/xbc.png')
        case 'xbp':
            return require('../../assets/coin-icons/xbp.png')
        case 'xby':
            return require('../../assets/coin-icons/xby.png')
        case 'xcp':
            return require('../../assets/coin-icons/xcp.png')
        case 'xdn':
            return require('../../assets/coin-icons/xdn.png')
        case 'xem':
            return require('../../assets/coin-icons/xem.png')
        case 'xin':
            return require('../../assets/coin-icons/xin.png')
        case 'xlm':
            return require('../../assets/coin-icons/xlm.png')
        case 'xmcc':
            return require('../../assets/coin-icons/xmcc.png')
        case 'xmg':
            return require('../../assets/coin-icons/xmg.png')
        case 'xmo':
            return require('../../assets/coin-icons/xmo.png')
        case 'xmr':
            return require('../../assets/coin-icons/xmr.png')
        case 'xmy':
            return require('../../assets/coin-icons/xmy.png')
        case 'xp':
            return require('../../assets/coin-icons/xp.png')
        case 'xpa':
            return require('../../assets/coin-icons/xpa.png')
        case 'xpm':
            return require('../../assets/coin-icons/xpm.png')
        case 'xrp':
            return require('../../assets/coin-icons/xrp.png')
        case 'xsg':
            return require('../../assets/coin-icons/xsg.png')
        case 'xtz':
            return require('../../assets/coin-icons/xtz.png')
        case 'xuc':
            return require('../../assets/coin-icons/xuc.png')
        case 'xvc':
            return require('../../assets/coin-icons/xvc.png')
        case 'xvg':
            return require('../../assets/coin-icons/xvg.png')
        case 'xzc':
            return require('../../assets/coin-icons/xzc.png')
        case 'yoyow':
            return require('../../assets/coin-icons/yoyow.png')
        case 'zcl':
            return require('../../assets/coin-icons/zcl.png')
        case 'zec':
            return require('../../assets/coin-icons/zec.png')
        case 'zel':
            return require('../../assets/coin-icons/zel.png')
        case 'zen':
            return require('../../assets/coin-icons/zen.png')
        case 'zest':
            return require('../../assets/coin-icons/zest.png')
        case 'zil':
            return require('../../assets/coin-icons/zil.png')
        case 'zilla':
            return require('../../assets/coin-icons/zilla.png')
        case 'zrx':
            return require('../../assets/coin-icons/zrx.png')
        default:
            return require('../../assets/coin-icons/generic.png')
    }
}