export const renderIcon = (slug : string) => {

    switch (slug.toLowerCase()) {
        case 'lithuania':
            return require(`../assets/lithuania.png`);
        case 'palau':
            return require(`../assets/palau.png`);
        case 'puerto-rico':
            return require(`../assets/puerto-rico.png`);
        case 'réunion':
            return require(`../assets/france.png`);
        case 'austria':
            return require(`../assets/austria.png`);
        case 'cuba':
            return require(`../assets/cuba.png`);
        case 'guernsey':
            return require(`../assets/guernsey.png`);
        case 'israel':
            return require(`../assets/israel.png`);
        case 'moldova':
            return require(`../assets/moldova.png`);
        case 'niger':
            return require(`../assets/niger.png`);
        case 'latvia':
            return require(`../assets/latvia.png`);
        case 'mauritius':
            return require(`../assets/mauritius.png`);
        case 'wallis-and-futuna-islands':
            return require(`../assets/france.png`);
        case 'botswana':
            return require(`../assets/botswana.png`);
        case 'gabon':
            return require(`../assets/gabon.png`);
        case 'ghana':
            return require(`../assets/ghana.png`);
        case 'switzerland':
            return require(`../assets/switzerland.png`);
        case 'syria':
            return require(`../assets/syria.png`);
        case 'togo':
            return require(`../assets/togo.png`);
        case 'nicaragua':
            return require(`../assets/nicaragua.png`);
        case 'taiwan':
            return require(`../assets/taiwan.png`);
        case 'uzbekistan':
            return require(`../assets/uzbekistan.png`);
        case 'afghanistan':
            return require(`../assets/afghanistan.png`);
        case 'djibouti':
            return require(`../assets/djibouti.png`);
        case 'greenland':
            return require(`../assets/greenland.png`);
        case 'cote-divoire':
            return require(`../assets/ivory-coast.png`);
        case 'guinea-bissau':
            return require(`../assets/guinea-bissau.png`);
        case 'hungary':
            return require(`../assets/hungary.png`);
        case 'korea-south':
            return require(`../assets/korea-south.png`);
        case 'rwanda':
            return require(`../assets/rwanda.png`);
        case 'antigua-and-barbuda':
            return require(`../assets/antigua-and-barbuda.png`);
        case 'british-indian-ocean-territory':
            return require(`../assets/british-indian-ocean-territory.png`);
        case 'cameroon':
            return require(`../assets/cameroon.png`);
        case 'slovenia':
            return require(`../assets/slovenia.png`);
        case 'equatorial-guinea':
            return require(`../assets/equatorial-guinea.png`);
        case 'madagascar':
            return require(`../assets/madagascar.png`);
        case 'tanzania':
            return require(`../assets/tanzania.png`);
        case 'timor-leste':
            return require(`../assets/timor-leste.png`);
        case 'heard-and-mcdonald-islands':
            return require(`../assets/australia.png`);
        case 'marshall-islands':
            return require(`../assets/marshall-islands.png`);
        case 'saint-kitts-and-nevis':
            return require(`../assets/saint-kitts-and-nevis.png`);
        case 'swaziland':
            return require(`../assets/swaziland.png`);
        case 'tajikistan':
            return require(`../assets/tajikistan.png`);
        case 'burkina-faso':
            return require(`../assets/burkina-faso.png`);
        case 'saint-martin-french-part':
            return require(`../assets/france.png`);
        case 'serbia':
            return require(`../assets/serbia.png`);
        case 'sudan':
            return require(`../assets/sudan.png`);
        case 'united-arab-emirates':
            return require(`../assets/united-arab-emirates.png`);
        case 'venezuela':
            return require(`../assets/venezuela.png`);
        case 'vietnam':
            return require(`../assets/vietnam.png`);
        case 'eritrea':
            return require(`../assets/eritrea.png`);
        case 'guinea':
            return require(`../assets/guinea.png`);
        case 'macedonia':
            return require(`../assets/macedonia.png`);
        case 'montserrat':
            return require(`../assets/montserrat.png`);
        case 'portugal':
            return require(`../assets/portugal.png`);
        case 'saint-lucia':
            return require(`../assets/saint-lucia.png`);
        case 'tokelau':
            return require(`../assets/tokelau.png`);
        case 'ireland':
            return require(`../assets/ireland.png`);
        case 'nigeria':
            return require(`../assets/nigeria.png`);
        case 'ecuador':
            return require(`../assets/ecuador.png`);
        case 'guyana':
            return require(`../assets/guyana.png`);
        case 'turkmenistan':
            return require(`../assets/turkmenistan.png`);
        case 'lesotho':
            return require(`../assets/lesotho.png`);
        case 'papua-new-guinea':
            return require(`../assets/papua-new-guinea.png`);
        case 'ethiopia':
            return require(`../assets/ethiopia.png`);
        case 'haiti':
            return require(`../assets/haiti.png`);
        case 'lebanon':
            return require(`../assets/lebanon.png`);
        case 'senegal':
            return require(`../assets/senegal.png`);
        case 'south-georgia-and-the-south-sandwich-islands':
            return require(`../assets/united-kingdom.png`);
        case 'tonga':
            return require(`../assets/tonga.png`);
        case 'cyprus':
            return require(`../assets/cyprus.png`);
        case 'dominica':
            return require(`../assets/dominica.png`);
        case 'liberia':
            return require(`../assets/liberia.png`);
        case 'yemen':
            return require(`../assets/yemen.png`);
        case 'kenya':
            return require(`../assets/kenya.png`);
        case 'argentina':
            return require(`../assets/argentina.png`);
        case 'kiribati':
            return require(`../assets/kiribati.png`);
        case 'lao-pdr':
            return require(`../assets/lao-pdr.png`);
        case 'libya':
            return require(`../assets/libya.png`);
        case 'saudi-arabia':
            return require(`../assets/saudi-arabia.png`);
        case 'australia':
            return require(`../assets/australia.png`);
        case 'burundi':
            return require(`../assets/burundi.png`);
        case 'cocos-keeling-islands':
            return require(`../assets/australia.png`);
        case 'saint-helena':
            return require(`../assets/united-kingdom.png`);
        case 'western-sahara':
            return require(`../assets/western-sahara.png`);
        case 'greece':
            return require(`../assets/greece.png`);
        case 'malta':
            return require(`../assets/malta.png`);
        case 'turkey':
            return require(`../assets/turkey.png`);
        case 'trinidad-and-tobago':
            return require(`../assets/trinidad-and-tobago.png`);
        case 'new-zealand':
            return require(`../assets/new-zealand.png`);
        case 'sao-tome-and-principe':
            return require(`../assets/sao-tome-and-principe.png`);
        case 'slovakia':
            return require(`../assets/slovakia.png`);
        case 'zambia':
            return require(`../assets/zambia.png`);
        case 'bouvet-island':
            return require(`../assets/norway.png`);
        case 'france':
            return require(`../assets/france.png`);
        case 'monaco':
            return require(`../assets/monaco.png`);
        case 'namibia':
            return require(`../assets/namibia.png`);
        case 'norway':
            return require(`../assets/norway.png`);
        case 'tuvalu':
            return require(`../assets/tuvalu.png`);
        case 'azerbaijan':
            return require(`../assets/azerbaijan.png`);
        case 'cayman-islands':
            return require(`../assets/cayman-islands.png`);
        case 'congo-brazzaville':
            return require(`../assets/congo-brazzaville.png`);
        case 'french-polynesia':
            return require(`../assets/french-polynesia.png`);
        case 'maldives':
            return require(`../assets/maldives.png`);
        case 'nauru':
            return require(`../assets/nauru.png`);
        case 'sweden':
            return require(`../assets/sweden.png`);
        case 'dominican-republic':
            return require(`../assets/dominican-republic.png`);
        case 'guadeloupe':
            return require(`../assets/france.png`);
        case 'mozambique':
            return require(`../assets/mozambique.png`);
        case 'chile':
            return require(`../assets/chile.png`);
        case 'faroe-islands':
            return require(`../assets/faroe-islands.png`);
        case 'montenegro':
            return require(`../assets/montenegro.png`);
        case 'bahamas':
            return require(`../assets/bahamas.png`);
        case 'cape-verde':
            return require(`../assets/cape-verde.png`);
        case 'georgia':
            return require(`../assets/georgia.png`);
        case 'saint-pierre-and-miquelon':
            return require(`../assets/france.png`);
        case 'italy':
            return require(`../assets/italy.png`);
        case 'micronesia':
            return require(`../assets/micronesia.png`);
        case 'bosnia-and-herzegovina':
            return require(`../assets/bosnia-and-herzegovina.png`);
        case 'brunei':
            return require(`../assets/brunei.png`);
        case 'canada':
            return require(`../assets/canada.png`);
        case 'myanmar':
            return require(`../assets/myanmar.png`);
        case 'somalia':
            return require(`../assets/somalia.png`);
        case 'belgium':
            return require(`../assets/belgium.png`);
        case 'el-salvador':
            return require(`../assets/el-salvador.png`);
        case 'isle-of-man':
            return require(`../assets/isle-of-man.png`);
        case 'jamaica':
            return require(`../assets/jamaica.png`);
        case 'mayotte':
            return require(`../assets/france.png`);
        case 'northern-mariana-islands':
            return require(`../assets/united-states.png`);
        case 'sri-lanka':
            return require(`../assets/sri-lanka.png`);
        case 'tunisia':
            return require(`../assets/tunisia.png`);
        case 'jersey':
            return require(`../assets/jersey.png`);
        case 'chad':
            return require(`../assets/chad.png`);
        case 'angola':
            return require(`../assets/angola.png`);
        case 'kuwait':
            return require(`../assets/kuwait.png`);
        case 'singapore':
            return require(`../assets/singapore.png`);
        case 'south-africa':
            return require(`../assets/south-africa.png`);
        case 'spain':
            return require(`../assets/spain.png`);
        case 'algeria':
            return require(`../assets/algeria.png`);
        case 'iran':
            return require(`../assets/iran.png`);
        case 'jordan':
            return require(`../assets/jordan.png`);
        case 'philippines':
            return require(`../assets/philippines.png`);
        case 'saint-vincent-and-the-grenadines':
            return require(`../assets/saint-vincent-and-the-grenadines.png`);
        case 'svalbard-and-jan-mayen-islands':
            return require(`../assets/norway.png`);
        case 'bahrain':
            return require(`../assets/bahrain.png`);
        case 'egypt':
            return require(`../assets/egypt.png`);
        case 'gibraltar':
            return require(`../assets/gibraltar.png`);
        case 'netherlands-antilles':
            return require(`../assets/netherlands.png`);
        case 'ukraine':
            return require(`../assets/ukraine.png`);
        case 'armenia':
            return require(`../assets/armenia.png`);
        case 'congo-kinshasa':
            return require(`../assets/congo-kinshasa.png`);
        case 'denmark':
            return require(`../assets/denmark.png`);
        case 'india':
            return require(`../assets/india.png`);
        case 'niue':
            return require(`../assets/niue.png`);
        case 'uruguay':
            return require(`../assets/uruguay.png`);
        case 'andorra':
            return require(`../assets/andorra.png`);
        case 'belize':
            return require(`../assets/belize.png`);
        case 'liechtenstein':
            return require(`../assets/liechtenstein.png`);
        case 'pitcairn':
            return require(`../assets/united-kingdom.png`);
        case 'antarctica':
            return require(`../assets/antarctica.png`);
        case 'benin':
            return require(`../assets/benin.png`);
        case 'french-guiana':
            return require(`../assets/france.png`);
        case 'kazakhstan':
            return require(`../assets/kazakhstan.png`);
        case 'bermuda':
            return require(`../assets/bermuda.png`);
        case 'falkland-islands-malvinas':
            return require(`../assets/united-kingdom.png`);
        case 'hong-kong-sar-china':
            return require(`../assets/hong-kong-sar-china.png`);
        case 'poland':
            return require(`../assets/poland.png`);
        case 'united-kingdom':
            return require(`../assets/united-kingdom.png`);
        case 'us-minor-outlying-islands':
            return require(`../assets/united-states.png`);
        case 'bolivia':
            return require(`../assets/bolivia.png`);
        case 'luxembourg':
            return require(`../assets/luxembourg.png`);
        case 'mali':
            return require(`../assets/mali.png`);
        case 'pakistan':
            return require(`../assets/pakistan.png`);
        case 'american-samoa':
            return require(`../assets/american-samoa.png`);
        case 'estonia':
            return require(`../assets/estonia.png`);
        case 'finland':
            return require(`../assets/finland.png`);
        case 'mongolia':
            return require(`../assets/mongolia.png`);
        case 'panama':
            return require(`../assets/panama.png`);
        case 'romania':
            return require(`../assets/romania.png`);
        case 'sierra-leone':
            return require(`../assets/sierra-leone.png`);
        case 'solomon-islands':
            return require(`../assets/solomon-islands.png`);
        case 'kosovo':
            return require(`../assets/kosovo.png`);
        case 'french-southern-territories':
            return require(`../assets/france.png`);
        case 'korea-north':
            return require(`../assets/korea-north.png`);
        case 'christmas-island':
            return require(`../assets/christmas-island.png`);
        case 'colombia':
            return require(`../assets/colombia.png`);
        case 'holy-see-vatican-city-state':
            return require(`../assets/holy-see-vatican-city-state.png`);
        case 'japan':
            return require(`../assets/japan.png`);
        case 'oman':
            return require(`../assets/oman.png`);
        case 'paraguay':
            return require(`../assets/paraguay.png`);
        case 'cambodia':
            return require(`../assets/cambodia.png`);
        case 'central-african-republic':
            return require(`../assets/central-african-republic.png`);
        case 'croatia':
            return require(`../assets/croatia.png`);
        case 'russia':
            return require(`../assets/russia.png`);
        case 'south-sudan':
            return require(`../assets/south-sudan.png`);
        case 'bangladesh':
            return require(`../assets/bangladesh.png`);
        case 'barbados':
            return require(`../assets/barbados.png`);
        case 'morocco':
            return require(`../assets/morocco.png`);
        case 'new-caledonia':
            return require(`../assets/france.png`);
        case 'zimbabwe':
            return require(`../assets/zimbabwe.png`);
        case 'bhutan':
            return require(`../assets/bhutan.png`);
        case 'macao-sar-china':
            return require(`../assets/macao-sar-china.png`);
        case 'united-states':
            return require(`../assets/united-states.png`);
        case 'aruba':
            return require(`../assets/aruba.png`);
        case 'czech-republic':
            return require(`../assets/czech-republic.png`);
        case 'comoros':
            return require(`../assets/comoros.png`);
        case 'guatemala':
            return require(`../assets/guatemala.png`);
        case 'norfolk-island':
            return require(`../assets/norfolk-island.png`);
        case 'saint-barthélemy':
            return require(`../assets/st-barts.png`);
        case 'belarus':
            return require(`../assets/belarus.png`);
        case 'virgin-islands':
            return require(`../assets/virgin-islands.png`);
        case 'germany':
            return require(`../assets/germany.png`);
        case 'honduras':
            return require(`../assets/honduras.png`);
        case 'iceland':
            return require(`../assets/iceland.png`);
        case 'indonesia':
            return require(`../assets/indonesia.png`);
        case 'nepal':
            return require(`../assets/nepal.png`);
        case 'peru':
            return require(`../assets/peru.png`);
        case 'samoa':
            return require(`../assets/samoa.png`);
        case 'thailand':
            return require(`../assets/thailand.png`);
        case 'brazil':
            return require(`../assets/brazil.png`);
        case 'british-virgin-islands':
            return require(`../assets/british-virgin-islands.png`);
        case 'iraq':
            return require(`../assets/iraq.png`);
        case 'malawi':
            return require(`../assets/malawi.png`);
        case 'anguilla':
            return require(`../assets/anguilla.png`);
        case 'bulgaria':
            return require(`../assets/bulgaria.png`);
        case 'china':
            return require(`../assets/china.png`);
        case 'costa-rica':
            return require(`../assets/costa-rica.png`);
        case 'grenada':
            return require(`../assets/grenada.png`);
        case 'guam':
            return require(`../assets/guam.png`);
        case 'kyrgyzstan':
            return require(`../assets/kyrgyzstan.png`);
        case 'martinique':
            return require(`../assets/martinique.png`);
        case 'mauritania':
            return require(`../assets/mauritania.png`);
        case 'qatar':
            return require(`../assets/qatar.png`);
        case 'mexico':
            return require(`../assets/mexico.png`);
        case 'san-marino':
            return require(`../assets/san-marino.png`);
        case 'suriname':
            return require(`../assets/suriname.png`);
        case 'albania':
            return require(`../assets/albania.png`);
        case 'gambia':
            return require(`../assets/gambia.png`);
        case 'netherlands':
            return require(`../assets/netherlands.png`);
        case 'palestine':
            return require(`../assets/palestine.png`);
        case 'uganda':
            return require(`../assets/uganda.png`);
        case 'malaysia':
            return require(`../assets/malaysia.png`);
        case 'vanuatu':
            return require(`../assets/vanuatu.png`);
        case 'ala-aland-islands':
            return require(`../assets/finland.png`);
        case 'cook-islands':
            return require(`../assets/cook-islands.png`);
        case 'fiji':
            return require(`../assets/fiji.png`);
        case 'seychelles':
            return require(`../assets/seychelles.png`);
        case 'turks-and-caicos-islands':
            return require(`../assets/united-kingdom.png`);
        default:
            return require(`../assets/question.png`);
    }   
}

